[package]
name = "combined-sink-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.10.4"
itertools = "0.11.0"
nom = "7.1.3"
